---
version: 2

jobs:
  test:
    working_directory: ~/helm.sh/helm
    docker:
      - image: circleci/golang:1.14

    environment:
      GOCACHE: "/tmp/go/cache"
      GOLANGCI_LINT_VERSION: "1.27.0"

    steps:
      - checkout
      - run:
          name: install test dependencies
          command: .circleci/bootstrap.sh
      - run:
          name: test style
          command: make test-style
      - run:
          name: test
          command: make test-coverage
  release:
    working_directory: ~/helm.sh/helm
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - run:
          name: License Scan
          command: |
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
            fossa analyze
            fossa test
      - run:
          name: Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test
